# Script to initiate the tests and report the coverage results
.test_template: &test_definition
  # only:
  #   - master
  #   - development
  script:
    - /opt/julia/bin/julia -e 'versioninfo()'
    - /opt/julia/bin/julia -e 'Pkg.clone(pwd()); Pkg.test("ControlToolbox",
      coverage = true)'
    - /opt/julia/bin/julia -e 'Pkg.add("Coverage"); cd(Pkg.dir("ControlToolbox"));
      using Coverage; cl, tl = get_summary(process_folder());
      println("(", cl/tl*100, "%) covered")'

test:0.3.12:
  image: julialang/julia:v0.3.12
  allow_failure: true
  <<: *test_definition

test:0.4.6:
  image: julialang/julia:v0.4.6
  allow_failure: true
  <<: *test_definition

test:0.5.0-dev:
  image: julialang/julia:v0.5.0-dev
  allow_failure: true
  <<: *test_definition
